### ISSUE TITLE
contenteditable="false" behavior

### ISSUE THREAD

**Issue by webdesserts** [guardian/scribe#411]
We're trying to use scribe to produce editable templates for our users that contain "variables" that can be automatically populated with data from our database. We originally tried ckeditor to achieve this and were able to do so by adding `contenteditable="false"` to a span with data attributes attached.

When I attempt to create a span with `contenteditable="false"` while using scribe the behavior isn't quite what I would expect. Here's a clip of what I'm seeing:

![scribe-contenteditable-bug](https://cloud.githubusercontent.com/assets/916253/8410978/06abe602-1e47-11e5-9f19-b0db86aeb227.gif)

There's three issues to note here:

1. After inserting an uneditable span with the `inserthtml` command, it seems that the cursor is placed inside the span (in the video I try to hit space multiple times immediately after inserting with no effect).
2. When trying to select an uneditable span the cursor always moves one extra character past the span.
3. When I attempt to delete anything in the editor, the span is removed (but not it's content), it doesn't mater where the cursor is placed. (this seems like a formatting cleanup issue?)

I could see how cursor placement could be my responsibility as a plugin editor, but the other two definitely seem like abnormal behavior.

I'm not quite sure on your stance on nested `contenteditable` regions. It seems you've done [some fixes](https://github.com/guardian/scribe/issues/308), but they seem specific to block elements. Is this something I could fix myself or is this a bug within scribe?

---

Here's the content of that variable plugin:

```js
  var command = new scribe.api.Command('insertHTML');

  command.execute = function (value) {
    scribe.api.Command.prototype.execute.call( this, '<span contenteditable="false">variable</span>')
  }

  scribe.commands['variable'] = command
```

**Comment by webdesserts** [comment]
Here's the [default behavior without scribe](http://jsbin.com/jiwowudoqu/edit?html,output)
Seems that issue 2 still exists, and again, issue 1 is probably just an issue with cursor placement. Issue 3 (which is the main problem) still exists.

**Comment by hmgibson23** [comment]
We've had a lot of issues with caret placement, maybe @cutandpastey and @redman can elaborate.

**Comment by robinedman** [comment]
Have you tried whether this works in a plain contenteditable in Firefox? (See https://bugzilla.mozilla.org/show_bug.cgi?id=685445).

If this doesn't work consistently across browsers the best approach might be to create a Scribe patch that implements the expected behaviour. 

We've implemented our own caret positioning in [scribe-plugin-noting](https://github.com/guardian/scribe-plugin-noting). The basic approach is to make use of zero width spaces to be able to place the caret where you want (since Chrome [normalises the cursor position](http://stackoverflow.com/questions/14347462/set-caret-position-in-contenteditable-div#comment19948776_14347462)), do anything you need to do (such as delete the contents of a span), then clean up after yourself.

**Comment by webdesserts** [comment]
Ok, just a quick run through testing out that jsbin in different browsers:

Firefox seems to be the main offender of *issue 2*, Chrome and Safari act fine. Also @robinedman, I took a look at it, and yes, that bug apparently still persists in Firefox. I don't have a means to test IE or mobile at the moment (our app is more of a desktop app so we don't develop for either). Chrome and Safari have another problem that I missed (with scribe) where the span is removed before the html is inserted.

![scribe-contenteditable-chrome-bug](https://cloud.githubusercontent.com/assets/916253/8414441/990ab38c-1e5d-11e5-9ad1-bb48ca5515ff.gif)

I'm going to create another jsbin with the scribe stuff for testing purposes and record any inconsistencies I find up top.

**Comment by webdesserts** [comment]
@robinedman also, thanks for pointing out the noting plugin. Since scribe's docs, and especially contenteditable's docs, still haven't been fleshed out, examples help tremendiously.

**Comment by bradvogel** [comment]
Try using an iframe instead, e.g. `<iframe srcdoc="variable"></iframe>`

**Comment by webdesserts** [comment]
@bradvogel the iframes do have something closer to the behavior I'm looking for though I will say I don't think we'd be too excited about the idea of scattering 20+ iframes across our document for single word spans (though I guess it's better than nothing).

Btw, we were able to accomplish this in Ckeditor with their [widgets](http://docs.ckeditor.com/#!/api/CKEDITOR.plugins.widget) it looks like they might have some of their own patches on top of `contenteditable="false"` that they used for the widget plugin.

**Comment by webdesserts** [comment]
`<input type="button" value="variable" />` is actually acting a bit closer to what I'm looking for without having to resort to iframes. We would just maybe have to fix some carret placement. I am having a problem with scribe preventing us from inserting an input in chrome, whereas input insertion works normally with a normal `contenteditable`. Any idea what might be causing scribe to prevent this?

**Comment by robinedman** [comment]
I suspect it's `scribe-plugin-sanitizer` getting in the way. You could try disabling it to see if that's the case.  

The sanitizer plugin uses `HtmlJanitor` which has whitelists of allowed elements. You might want to add BUTTON as an allowed tag [there](https://github.com/guardian/html-janitor/blob/master/src/html-janitor.js) or potentially [in the sanitizer plugin itself](https://github.com/guardian/scribe-plugin-sanitizer/blob/master/src/scribe-plugin-sanitizer.js).

**Comment by rrees** [comment]
You can embed a contenteditable="false" inside a contenteditable="true"?

![](http://i.giphy.com/5aLrlDiJPMPFS.gif)

**Comment by rrees** [comment]
@robinedman @webdesserts I'm not sure the sanitizer is a default plugin, could you point us towards an example page or share the config you're trying to use?

**Comment by webdesserts** [comment]
@robinedman @rees I figured it out, it was an issue with my jsbin, not scribe, so it's just the weird behavior with firefox caret placement.

**Comment by webdesserts** [comment]
So we went and did some research into which weird elements worked best for our purposes. We're going to try out using an `input[type=text,disabled]` because it's probably the least horrible of the available solutions where we didn't need to patch too many things. Thought y'all might find some use in the data we collected so here's our [google doc](https://docs.google.com/spreadsheets/d/1hGCC4hIHz00_pLSDpRZp9wnXr1tMvn0CItpDpf1gVq4/edit?usp=sharing).

**Comment by timmyg** [comment]
@webdesserts do you have a demo of the implementation of the "add variable" that you have in your clip? Am trying to do just that but having issues.

**Comment by webdesserts** [comment]
@timmyg This was the code I tested everything in the notes with: http://jsbin.com/piyeka/33/edit?html,css,js,output (not what's in the original screenshot though)

**Comment by timmyg** [comment]
@webdesserts awesome! exactly what I needed. Did you play around with drag/drop at all?

**Comment by webdesserts** [comment]
@timmyg I did not, sorry. That project got put on hold.
